## Features Engineering

In [2]:
import re

num = re.compile('\d+\.\d+')
gr = re.search(num, 'Temp 2.2 C')
gr.group(0)

'2.2'

## Features Selection
Remove high correlated features

In [3]:
from sklearn.datasets import load_wine
import numpy as np

cor_thres = 0.5
X, y = load_wine(return_X_y=True, as_frame=True)
cor = X.corr()
lower_cor = cor.mask( (np.triu(cor) != 0) )
col_cor = lower_cor[lower_cor.abs() > cor_thres].dropna(how='all')
col_cor.notna().sum(axis=1).sort_values(ascending = False)

od280/od315_of_diluted_wines    5
hue                             3
proanthocyanins                 2
flavanoids                      1
nonflavanoid_phenols            1
color_intensity                 1
proline                         1
dtype: int64

## TF-IDF  
with term _t_ from doccument _d_ from universe doccuments _D_  
$tf(t, d) = log(1 + \frac{n(t)}{n(d)})$  
$idf(t, D) = log(\frac{n(D)}{n(t in d)})$

In [5]:
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [32]:
docs=["the house had a tiny little mouse", 
"the cat saw the mouse", 
"the mouse ran away from the house", 
"the cat finally ate the mouse", 
"the end of the mouse story"]

In [28]:
cv = CountVectorizer()
wc = cv.fit_transform(docs)
print(wc.shape); print(wc.toarray())

(5, 16)
[[0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 1]
 [0 0 1 0 0 0 0 0 0 1 0 0 1 0 2 0]
 [0 1 0 0 0 1 0 1 0 1 0 1 0 0 2 0]
 [1 0 1 0 1 0 0 0 0 1 0 0 0 0 2 0]
 [0 0 0 1 0 0 0 0 0 1 1 0 0 1 2 0]]


In [27]:
all_word = []
for t in docs:
    all_word += (t.split())
print(len(set(all_word))); print(set(all_word))

17
{'ran', 'house', 'had', 'end', 'cat', 'saw', 'story', 'little', 'tiny', 'the', 'from', 'away', 'ate', 'mouse', 'a', 'of', 'finally'}
